baseURL = "https://fll-skane.github.io/fllskane-hugo/"
languageCode = "en-us"
publishDir = "docs"
sectionPagesMenu = "main"
theme = "ananke"
title = "FLL Skåne Hugo Site"
[[menu.main]]
name = "Google"
url = "google.com"
weight = 2
